@RPG_Login_API_HostAddress = https://localhost:7127

### Login and registration

# @name login
POST {{RPG_Login_API_HostAddress}}/api/users/login
Content-Type: application/json
Accept: application/json
{
  "Username": "testusername",
  "Password": "Testpassword1!"
}

###

# @name login
POST {{RPG_Login_API_HostAddress}}/api/users/login
Content-Type: application/json
Accept: application/json
{
  "Username": "seconduser",
  "Password": "Secondpassword2@"
}

###

# @name login
POST {{RPG_Login_API_HostAddress}}/api/users/login/refresh
Content-Type: application/json
Accept: application/json
{
  "RefreshToken": "{{login.response.body.$.RefreshToken}}"
}

###

# @name login
POST {{RPG_Login_API_HostAddress}}/api/users/register
Content-Type: application/json
Accept: application/json
{
  "Username": "seconduser",
  "Email": "seconduser@gmail.com",
  "Password": "Secondpassword2@"
}

###

POST {{RPG_Login_API_HostAddress}}/api/users/logout
Authorization: Bearer {{login.response.body.$.AccessToken}}
Content-Type: application/json
Accept: application/json
###



### User requests (pass access token as bearer)

GET {{RPG_Login_API_HostAddress}}/api/users/characters
Authorization: Bearer {{login.response.body.$.AccessToken}}
Accept: application/json
###

