services:
  rpg_login_api:
    image: ${DOCKER_REGISTRY-}rpgloginapi
    build:
      context: .
      dockerfile: RPG_Login_API/Dockerfile
    networks:
      - network-rpg-login-api

networks:
  network-rpg-login-api:
    name: network-rpg-login-api
